### ISSUE TITLE
the animated Fab?

### ISSUE THREAD

**Issue by BeanWei** [MarcinusX/flutter_ui_challenge_filter_menu#2]
this project so cool, I see the detail at your blog.

About the animated Floating Action Button,  when we tap the Base Fab, will expanded, right? Then we will see more Fab, when it unexpanded, the Fabs are hidden, we just see the base Fab. 

But its still work when the Fabs hidden, I mean we could touch inadvertently when the Fabs are hidden.

I don't know whether my expression clear.

**Comment by MarcinusX** [comment]
Oh, nice one. :)
I will take a look at it in a few days and see what we can do :)

**Comment by BeanWei** [comment]
if (_animationController.value == 0) {
      return null;
    } else {...}

return null, the button will disabled, but we still can see the shadow when click the Fabs.

**Comment by MarcinusX** [comment]
@BeanWei Thank you very much for pointing it out :)
I fixed it with this:
```
if (_animationController.isDismissed) {
    return Container();
}
```

**Comment by BeanWei** [comment]
@MarcinusX Oh, cool. "return Container" is better. 👍
